language: go
sudo: false
matrix:
  include:
    - go: 1.16.x

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mitchellh/gox

script:
  - |-
    gox \
      -os="darwin" -os="linux" -os="windows" -os="freebsd" -os="netbsd" -os="openbsd" -arch="amd64" -arch="arm64" -osarch="linux/386" -osarch="windows/386" \
      -output="build/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}" \
      -ldflags " \
        -X github.com/prometheus/common/version.Revision=${TRAVIS_COMMIT} \
        -X github.com/prometheus/common/version.Version=${TRAVIS_TAG} \
        -X github.com/prometheus/common/version.Branch=${TRAVIS_BRANCH} \
        -X github.com/prometheus/common/version.BuildDate=$(date +'%Y-%m-%d_%H:%M:%S') \
        -X github.com/prometheus/common/version.BuildUser=${USER} \
       "

before_deploy:
  - cd build
  - chmod +x ./*
  - for f in *; do tar -czf $f.tar.gz $f && rm $f; done
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: "CPOY8FHFOETTwYdcfrpxgl4j34As0Dvk8t+gDiod9Pl9v7BmV8FtDAi0KHavNTpboF+OGPbbPK0aCaFH8KGGUUWr1fJUBpYRpH0npqSQ0xGCaaPsQ2tBUfFYN3NoH6iBGqLA2DBR3i3jxCUzoUJG0lSoCmfSJXRU3bywQIpxflbHZHunT/GetUHN0xFN7azBUSg6KHJH3OrQDXkWXyug7alUkjAtMjqC6RQxSmXmTAv2z2cO5V8dOc59kd0u5mDAsjcC0aJ3tl0lvW4zKsRKhsI3X6WwTqNkn/+r3xYuSlF/8HnBvWcoKBe1ZBLzdVSvf1eWjPefm1GC9fGsALQlzJr5DQqOYeO51TdUOBURiOfMyvail0lIKOYtguWkvrmhnrr1sqh2M9nntLBryh0fKCiFYBlJkc8epGNHm9kuKcD+PR9OS+G214lOwttCzW+R6z0OXFq761jIcHlZpkD4H0lCSCjRqRuRAWq0mk1Wq49FUKUyu7ncprGz442FzZDQd0RUJfqr6bpAnSYIzf3ccK2qvRdFJaHFr6huaeO3Cqup0nsAvbxGCN5469e5BQrS6+N6/kv1746Yyo+iqvR/LFZcXaeexcpN9XxMRlQsXjEm+dYyFjEi4Tmce/K9jxtYzKgWhEaqvQirOkB7B7pESnu8ZglXti/eh4MkIAkfsn8="
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: xxxcoltxxx/selectel-balance-exporter
