language: go
sudo: false
matrix:
  include:
    - go: 1.16.x

env:
  matrix:
    - GO111MODULE=on
  global:
    secure: CoAEnAQnqjCyir3NvRnS4vplrWUZxa0fsxsFWSUknJu3Mbdhcsu+rb9Hq+NgjHNemzhAfQSiPLe3uqwWBZQg6oo2DfRMKv/CxgpiMb0t7aUJ1jrrNITe1reInWGBGEUwHXgCy2BAQQuKeHodknt0W2fHFCyhPBfj71B8uwLwff7jRz9aZH7IGURX0OYpjvUbJf2iR4Gos+JSmhwo9UUkEj40MTr6EEmGGZ2xUZ3Pef2qehOjJ/1HeCWyKqLDCTobmXN+ufQyA7pjauAcjYmilOJXVlvzKlRzkiPeejEunND0HHBU7iMaeTDCUFqBWxf9jfeeClzgFYG56JBpJ0TmvROpm5HGQb/gC5pIqtZYraT7hMfGZXhfzn8kXh/AM0ULtjCJD57OgKmfUoxkfs0FuPBMwmeFhaVe6+IZZWZIYgw5GmEfb3uWeDamgfUFzLl5pIfQ284K3mbBvjlgCwZKZRnpHGrpv7ru25FEHnVMRR4Mkrq1N+pkgh8venvHOlEEQQ5qKdkDTbFmMFFErb/z37BYI4G20w22tQQiy7XbgduoPK+WtM1a2cE6AQ1Wt4bHB8Z2kQv4/k13CBHASg4S2+/TBNHQQylxH8F5YOVWFgfdsV2YIr4YTsapXZyJKwvAtclB3ZoQgqgdigWRBUQNvXkVHBwajskx/Xpzi6WBOb0=

before_install:
  - go get github.com/mitchellh/gox

script:
  - |-
    gox \
      -os="darwin" -os="linux" -os="windows" -os="freebsd" -os="netbsd" -os="openbsd" -arch="amd64" -arch="arm64" -osarch="linux/386" -osarch="windows/386" \
      -output="build/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}" \
      -ldflags " \
        -X github.com/prometheus/common/version.Revision=${TRAVIS_COMMIT} \
        -X github.com/prometheus/common/version.Version=${TRAVIS_TAG} \
        -X github.com/prometheus/common/version.Branch=${TRAVIS_BRANCH} \
        -X github.com/prometheus/common/version.BuildDate=$(date +'%Y-%m-%d_%H:%M:%S') \
        -X github.com/prometheus/common/version.BuildUser=${USER} \
       "

before_deploy:
  - cd build
  - chmod +x ./*
  - for f in *; do tar -czf $f.tar.gz $f && rm $f; done
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: cyDKM/nUkx/490hxSrq7t1G4JmOtb++Or5zDoBR0hTEkWQ+bvEe5eg4OlyFfkgJZLYYNEhDpLPX9xi25HqJo8qdDCwJ3jNpPVb2xY4sJsplfW4+meZJlWX3kioiMYKk2v/67ewu5Kq49Kioh1U/0nTAH9yzKCJxZ17SVg76N+we3L77C85YUqCEyBOvSYi7wg/QC30/mG0ZbWLWloVpthH9uxvdCL4Xm3LfQSA83z0k6mLN1TurA+BIXI3gfZR//Ef7QZ34fx8z1iZ789B7mbntPZkcS3CSo/dBLPzDTciJx0MYWSnAEkmESN9a/icKFI1Q/9Z/UN+SQOaYoqtQuOmjr4gVfwBJdumyIv9kPqNK6++y0/Fw/jm51FvxWU3Sfqo70PNztiBaNeMbZoNYqbNlRlSLkX3s2pGcoh0l7SOTR41nzx2lVTnRs8vTER+WhYaJW8ILfNX9e7oKkWVlIQle6rfk3zFaMBdRKtQW6r4GgExZZKliHg7+6OLShA5znUoX4mf6yJy/4G6HTGRsYQN6YcjZq32bFOQehpSeon7woRpK49KdqCJjxoS5PlmAto0+LzFO1YdBHDO/olr6lZcIL6oR/JlBi2uAZie2/W0afLvS3D8tkUskq8CJIaE+43ZH/tPKLMzUxcO5bCuTzs8OCsSOu/r/H6FKZBMq7O28=
  file_glob: true
  file: build/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: xxxcoltxxx/selectel-balance-exporter
